
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: protospace_38584_development

test:
  <<: *default
  database: protospace_38584_test


production:
  <<: *default
  database: protospace_38584_production
  username: protospace_38584
  password: <%= ENV['PROTOSPACE_38584_DATABASE_PASSWORD'] %>
